<?php

namespace Tests\Feature;

use App\Services\CriadorDeSerie;
use App\Services\removedorDeSerie;
use Tests\TestCase;
use Illuminate\Foundation\Testing\WithFaker;
use Illuminate\Foundation\Testing\RefreshDatabase;

class RemovedorDeSeriesTest extends TestCase
{
    use RefreshDatabase;
    /** @var Serie */
    private $serie;
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $criadorDeSerie = new CriadorDeSerie();
        $nomeSerie = 'teste';
       $this->serie = $criadorDeSerie->criarSerie($nomeSerie,1,1);
    }

    public function testRemoverUmaSerie()
    {
        $this->assertDatabaseHas('series', ['id' => $this->serie->id]);
        $removedorDeSerie = new removedorDeSerie();
        $nomeSerie = $removedorDeSerie->removerSerie($this->serie->id);
        $this->assertIsString($nomeSerie);
        $this->assertEquals('teste', $this->serie->nome);
        $this->assertDatabaseMissing('series', ['id' => $this->serie->id]);
    }
}
